---
sources:
    - name: cpu_source
      interval: 600
      meters:
          - "cpu"
      sinks:
          - cpu_sink
sinks:
    - name: cpu_sink
      transformers:
      publishers:
          - monclient://http://192.168.10.4:8080/v2.0?username=xxxx&password=yyyy
